IndusIndIMPSAdminPortal/IndusIndIMPSAdminPortal/Controllers/NBINController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EntityLayer;
using IndusIndIMPSAdminPortal.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace IndusIndIMPSAdminPortal.Controllers
{
    public class NBINController : Controller
    {
       NBINModel model = new NBINModel();
        private readonly ILogger<Program> logger;
        public ActionResult Index()
        {
          
            NBINModel EntityModel = new NBINModel();
            
            return View();
           
        }

        [HttpGet]
        public JsonResult getAllNBIN()
        {
            Response res = new Response();
            res.ResponseStatus = true;
            res.ResponseMessage = "NBIN data not found";
            try
            {
                NBINModel EntityModel = new NBINModel();
                res.ResponseData = EntityModel.GetNBINList();
                res.ResponseMessage = "Success";
            }
            catch (Exception ex)
            {
                res.ResponseMessage = "Something went wrong";
            }
            return Json(res);
        }

        [HttpPost]
        public JsonResult CreateNBIN([FromBody] NBINEL data)
        {
            Response response = new Response();
            try
            {
                response = model.Create(data);
                return Json(response);

                /*if (model.Create(data).ResponseStatus)
                {
                    response.ResponseStatus = true;

                    //response.ResponseMessage = "NBIN created successfully";
                    //ViewBag.Message = HttpContext.Session.ToString("NBIN created successfully"); 
                    return Json(response);
                }
                else
                {
                    response.ResponseStatus = false;
                    response.ResponseMessage = "NBIN Creation Failed";
                }*/
            }
            catch (Exception ex)
            {
                response.ResponseStatus = false;
                response.ResponseMessage = "Task can't be performed due to some error";
                
            }
            //response = model.Create(data);
            
            return Json(response);
        }

        
        [HttpPost]
        public JsonResult EditNBIN([FromBody] NBINEL Bank_ID)
        {
            Response res = new Response();
            try
            {
                NBINViewModel editlist = new NBINViewModel();
                res = model.GetNBINbyId(Convert.ToInt32(Bank_ID.BANKID));

            }
            catch (Exception ex)
            {
                res.ResponseMessage = "Task can't be performed due to some error";
                res.ResponseStatus = false;
            }
            return Json(res);
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public Response UpdateNBIN([FromBody] NBINEL NBINdata)
        {
            Response res = new Response();
            try
            {
                res= model.UpdateNBIN(NBINdata);
            }
            catch (Exception ex)
            {
                res.ResponseMessage = "Task can't be performed due to some error";
                res.ResponseStatus = false;
            }
            return res;
        }

        [HttpPost]
        public JsonResult CheckNBIN(NBINEL data)
        {
            Response res = new Response();
            try
            {
                string strnbin = data.NBIN;
                int IntChecker = 7676;// data.CREATEDBY;
                string feedback = data.REJECTION_DESP;
                res = model.CheckNBIN(strnbin, IntChecker, feedback);
            }
            catch (Exception ex)
            {
                res.ResponseMessage = "Task can't be performed due to some error";
                res.ResponseStatus = false;
            }
            return Json(res);
        }

    }
}

IndusIndIMPSAdminPortal/IndusIndIMPSAdminPortal/Controllers/PartnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using IndusIndIMPSAdminPortal.Models;
using EntityLayer;

namespace IndusIndIMPSAdminPortal.Controllers
{
    public class PartnerController : Controller
    {
        public IActionResult PartnerManagement()
        {
            PartnerModel partnerModelCall = new PartnerModel();
            //PartnerViewModel partnerInfo = partnerModelCall.GetPartnerList();
            List<PartnerEL> partnerInfo = partnerModelCall.GetPartnerList();
            return View(partnerInfo);
        }

        [HttpPost]
        public JsonResult GetPartnerById(int PartnerId)
        {
            //PartnerEL partnerInfo = new PartnerEL();
            //partnerInfo.Partner_Id = PartnerId;
            PartnerModel partnerModelCall = new PartnerModel();

            List<PartnerEL> partnerInfo = partnerModelCall.GetPartnerById(PartnerId);

            return Json(partnerInfo);
        }


        [HttpPost]
        public JsonResult InsertPartner(PartnerEL partnerData)
        {
            //PartnerModel objInsertPartner = new PartnerModel();
            //string response = objInsertPartner.insertPartner(partnerData);
            //return Json(response);
            //return RedirectToAction("PartnerManagement");

            PartnerModel objInsertPartner = new PartnerModel();
            Response ObjResponse = new Response();

            try
            {
                var valid = TryValidateModel(partnerData);
                if (valid)
                {
                    
                    ObjResponse = objInsertPartner.insertPartner(partnerData);
                }
                else
                {
                    String messages = String.Join(Environment.NewLine, ModelState.Values.SelectMany(v => v.Errors).Take(1)
                                                           .Select(v => v.ErrorMessage + " " + v.Exception));

                    //string ss = String.Join(Environment.NewLine, ModelState.Values.SelectMany(v => v.Errors)
                    //                                       .Select(v => v.ErrorMessage + " " + v.Exception));

                    ObjResponse.ResponseMessage = messages;
                }
            }
            catch (Exception ex)
            {
                ObjResponse.ResponseMessage = "Exception in InsertPartner :" + ex;
            }
            return Json(ObjResponse);
        

    }

        [HttpPost]
        public JsonResult UpdatePartner(PartnerEL partnerData)
        {
            //PartnerModel objUpdatePartner = new PartnerModel();
            //string response = objUpdatePartner.updatePartner(partnerData);
            //return Json(response);

            PartnerModel objUpdatePartner = new PartnerModel();
            Response ObjResponse = new Response();

            try
            {
                var valid = TryValidateModel(partnerData);
                if (valid)
                {

                    ObjResponse = objUpdatePartner.updatePartner(partnerData);
                }
                else
                {
                    String messages = String.Join(Environment.NewLine, ModelState.Values.SelectMany(v => v.Errors).Take(1)
                                                           .Select(v => v.ErrorMessage + " " + v.Exception));
                    ObjResponse.ResponseMessage = messages;
                }
            }
            catch (Exception ex)
            {
                ObjResponse.ResponseMessage = "Exception in InsertPartner :" + ex;
            }
            return Json(ObjResponse);

        }

        [HttpPost]
        public JsonResult DeletePartner(PartnerEL partnerData)
        {
            PartnerModel objDeletePartner = new PartnerModel();
            string response = objDeletePartner.deletePartner(partnerData);
            return Json(response);
        }

        [HttpPost]
        public JsonResult CheckPartner(PartnerEL partnerData)
        {
            PartnerModel objCheckPartner = new PartnerModel();
            string response = objCheckPartner.checkPartner(partnerData);
            return Json(response);
        }

        [HttpPost]
        public JsonResult RejectPartner(PartnerEL partnerData)
        {
            PartnerModel objRejectPartner = new PartnerModel();
            string response = objRejectPartner.rejectPartner(partnerData);
            return Json(response);
        }


    }
}

IndusIndIMPSAdminPortal/IndusIndIMPSAdminPortal/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CommonLayer;
using EntityLayer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace IndusIndIMPSAdminPortal
{
    public class RoleController : Controller
    {
        #region RoleManagement
        public ActionResult RoleManagement()
        {
            Response res = new Response();
            List<Role> list = new List<Role>();
            try
            {
                // ViewData["RoleList"] = RoleModel.GetAllRole();
                res.ResponseData = RoleModel.GetAllRole();
            }
            catch (Exception ex)
            {
                //ObjResponse.ResponseMessage = ConstantResponseMsg.ControllerError;
            }
            return View();
        }
        #endregion
        #region RoleList
        [HttpGet]
        public JsonResult getRoleList()
        {
            Response res = new Response();
            res.ResponseStatus = true;
            res.ResponseMessage = "Data can't fetch";
            try
            {
                // ViewData["RoleList"] = RoleModel.GetAllRole();
                res.ResponseData = RoleModel.GetAllRole();
                res.ResponseStatus = true;
                res.ResponseMessage = "Success Role List";
            }
            catch (Exception ex)
            {
                //ObjResponse.ResponseMessage = ConstantResponseMsg.ControllerError;
            }
            return Json(res);
        }
        #endregion

        #region SaveRole
        [HttpPost]
        public JsonResult SaveRole([FromBody] Role ObjRoleModel)
        {
            Response ObjResponse = new Response();
            try
            {
                var valid = TryValidateModel(ObjRoleModel);
                if (valid)
                {
                    ObjRoleModel.UserId = HttpContext.Session.GetString("LoginUser");
                    ObjResponse = RoleModel.SaveRole(ObjRoleModel);
                }
                else
                {
                    ObjResponse.ResponseMessage = String.Join(Environment.NewLine, ModelState.Values.SelectMany(v => v.Errors).Take(1)
                                                           .Select(v => v.ErrorMessage + " " + v.Exception));
                }
            }
            catch (Exception ex)
            {
                ObjResponse.ResponseMessage = ConstantResponseMsg.ControllerError;
            }
            return Json(ObjResponse);
        }
        #endregion

        #region GetSingleRole
        [HttpPost]
        public JsonResult GetSingleRole([FromBody] Role RoleData)
        {
            Response ObjResponse = new Response();
            try
            {
                //HttpContext.Session.GetString("LoginUser");
                //int roleId = Convert.ToInt32(RoleId);
                ObjResponse = RoleModel.GetSingleRole(Convert.ToInt32(RoleData.RoleId));
            }
            catch (Exception ex)
            {
                ObjResponse.ResponseMessage = ConstantResponseMsg.ControllerError;
            }
            return Json(ObjResponse);
        }
        #endregion

        #region DeleteRole
        [HttpPost]
        public JsonResult DeleteRole([FromBody] Role ObjRoleModel)
        {
            Response ObjResponse = new Response();
            try
            {
                string userId = HttpContext.Session.GetString("LoginUser");
                // int roleId = Convert.ToInt32(RoleId);
                ObjResponse = RoleModel.DeleteRole(Convert.ToInt32(ObjRoleModel.RoleId), userId);
            }
            catch (Exception ex)
            {
                ObjResponse.ResponseMessage = ConstantResponseMsg.ControllerError;
            }
            return Json(ObjResponse);
        }
        #endregion


        #region UpdateRole
        [HttpPost]
        public JsonResult UpdateRoleName([FromBody]Role ObjRoleModel)
        {
            Response ObjResponse = new Response();
            try
            {
                ObjRoleModel.UserId = "Sandeep";// HttpContext.Session.GetString("LoginUser");
                // int roleId = Convert.ToInt32(RoleId);
                ObjResponse = RoleModel.UpdateRole(ObjRoleModel);
            }
            catch (Exception ex)
            {
                ObjResponse.ResponseMessage = ConstantResponseMsg.ControllerError;
            }
            return Json(ObjResponse);
        }
        #endregion
    }
}

IndusIndIMPSAdminPortal/IndusIndIMPSAdminPortal/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using IndusIndIMPSAdminPortal.Models;
using EntityLayer;

namespace IndusIndIMPSAdminPortal.Controllers
{
    public class UserController : Controller
    {
        public IActionResult UserManagement()
        {
            UserModel objUserList = new UserModel();
            List<UserEL> userInfo = objUserList.GetUserList();
            return View(userInfo);
        }

        [HttpPost]
        public JsonResult GetUserById(UserEL User)
        {
            UserModel objUser = new UserModel();
            Response ObjResponse = new Response();
            ObjResponse = objUser.GetUserById(User);
            return Json(ObjResponse);
        }

        [HttpPost]
        public JsonResult CreateUser(UserEL data)
        {
            UserModel objCreateUser = new UserModel();
            Response ObjResponse = new Response();
            try
            {
                var remoteIpAddress  = HttpContext.Connection.RemoteIpAddress;
                var valid = TryValidateModel(data);
                if (valid)
                {
                    data.Client_IP = remoteIpAddress.ToString();
                    ObjResponse = objCreateUser.createUser(data);
                }
                else
                {
                    String messages = String.Join(Environment.NewLine, ModelState.Values.SelectMany(v => v.Errors).Take(1)
                                                           .Select(v => v.ErrorMessage + " " + v.Exception));
                    ObjResponse.ResponseMessage = messages;
                }
            }
            catch (Exception ex)
            {
                ObjResponse.ResponseMessage = "Exception in InsertPartner :" + ex;
            }
            return Json(ObjResponse);
        }

        [HttpPost]
        public JsonResult UpdateUser(UserEL data)
        {
            UserModel objUpdateUser = new UserModel();
            Response ObjResponse = new Response();
            //ObjResponse = objUpdateUser.updateUser(data);
            try
            {
                var valid = TryValidateModel(data);
                if (valid)
                {
                    ObjResponse = objUpdateUser.updateUser(data);
                }
                else
                {
                    String messages = String.Join(Environment.NewLine, ModelState.Values.SelectMany(v => v.Errors).Take(1)
                                                           .Select(v => v.ErrorMessage + " " + v.Exception));
                    ObjResponse.ResponseMessage = messages;
                }
            }
            catch (Exception ex)
            {
                ObjResponse.ResponseMessage = "Exception in InsertPartner :" + ex;
            }
            return Json(ObjResponse);
        }

        [HttpPost]
        public JsonResult DeleteUser(UserEL data)
        {
            UserModel objDeleteUser = new UserModel();
            Response ObjResponse = new Response();
            ObjResponse = objDeleteUser.deleteUser(data);
            return Json(ObjResponse);
        }

    }
}

IndusIndIMPSAdminPortal/IndusIndIMPSAdminPortal/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Indusind Recon Panel</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link href="~/assets/css/fonts.googleapis.css" rel="stylesheet" />
    <link href="~/assets/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/assets/css/stackpath.bootstrapcdn.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="~/assets/css/bootstrap/bootstrap-grid.min.css" />
    <link rel="stylesheet" type="text/css" href="~/assets/css/bootstrap/bootstrap-reboot.min.css" />
    <link rel="stylesheet" type="text/css" href="~/assets/css/bootstrap/bootstrap.min.css" />
    <link href="~/assets/css/datepicker.css" rel="stylesheet" />
    <link href="~/assets/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/assets/css/buttons.bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="~/assets/css/style.css" />
    <link href="~/css/MyCSS.css" rel="stylesheet" />


    @*Script*@
    @section scripts{
        <script src="~/assets/js/jquery-3.3.1.js"></script>
        <script src="~/js/jquery.blockUI.min.js"></script>
        <script type="text/javascript" src="~/assets/js/script.js"></script>
        <script type="text/javascript" src="~/assets/js/bootstrap.min.js"></script>
        <script src="~/assets/js/jquery.dataTables.min.js"></script>
        <script src="~/assets/js/dataTables.bootstrap4.min.js"></script>
        <script src="~/assets/js/bootstrap-datepicker.js"></script>
        <script type="text/javascript" src="~/assets/js/script.js"></script>
        <script src="~/js/Helper/Main.js"></script>
        <script src="~/js/Helper/CustomFunction.js"></script>
        <script src="~/js/Login.js"></script>

    }


</head>


<body class="dashboard">
    <header class="header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-2 logo p-0">
                    <img src="~/assets/images/logo.jpg" alt="logo" style="width:100%" />

                </div>
                
                <div class="col-8 text-center align-self-center">
                   <div class="main-title">IMPS RECON PANEL</div>

                </div>
                <div class="col-2 text-center">
                    @if (@HttpContextAccessor.HttpContext.Session.GetString("LoginUser") == null)
                    {
                        <div class="user-login" id="HoverLogout">
                            <span class="user-icon"><img src="~/assets/images/user-circle-gray.svg" alt="user login" /></span>  <span><img src="~/assets/images/angle-down.svg" alt="down angle"></span>
                        </div>
                    }
                    else
                    {
                        <div class="user-login" id="HoverLogout">

                            <span class="user-icon"><img src="~/assets/images/user-circle-gray.svg" alt="user login" /></span><button class="logoutdropbtn"><b> @Context.Session.GetString("LoginUser")</b></button> <span><img src="~/assets/images/angle-down.svg" alt="down angle"></span>
                            @*<div class="dropdown-content">
                       <a href="@Url.ActionLink("Logout", "Login")"><b>Logout</b></a>
                    </div>*@
                        </div>

                    }
                    @*<div class="user-login">
                <span class="user-icon"><img src="~/assets/images/user-circle-gray.svg" alt="user login" /></span> Antonin Hafer <span><img src="~/assets/images/angle-down.svg" alt="down angle"></span>
            </div>*@

                </div>
            </div>
        </div>
    </header>
    <div class="user-options ChangeLogout" id="showLogout">
        <a class="alogout" href="@Url.ActionLink("Logout", "Login")"><b style="text-decoration:none">Logout</b></a>
        @*<ul>
                <li>Logout</li>
            </ul>*@
    </div>
    @*<div class="user-options" style="display:block">
            <div>
                <a href="@Url.ActionLink("Logout", "Login")"><b>Logout</b></a>
            </div>
        </div>*@
    @*<div id="ShowLogout" class="user-options" style="display:block">
                <div class="dropdown-content">
                    <a href="@Url.ActionLink("Logout", "Login")"><b>Logout</b></a>
                </div>
        </div>*@
    @*<div class="user-options" style="display:block">
            <ul>
                    <li href="@Url.ActionLink("Logout", "Login")"><b>Logout</b></li>
                </ul>
            <ul>
                <li>
                    <a href="@Url.ActionLink("Logout", "Login")"><b>Logout</b></a>
                </li>
             </ul>
        </div>*@
    <nav class="navbar navbar-expand-md navbar-light bg-white">
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="col-12 collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav">
                <a id="Dash_ID" href="@Url.Action("Index","Home")" class="nav-item nav-link ">
                    <i class="fa fa-tachometer" aria-hidden="true"></i> Dashboard
                </a>
                <a id="RM_ID" href="@Url.Action("RoleManagement","Role")" class="nav-item nav-link ">
                    <i class="fa fa-cog" aria-hidden="true"></i> Role Management
                </a>
                <a id="UM_ID" href="@Url.Action("UserManagement","User")" class="nav-item nav-link">
                    <i class="fa fa-user-o" aria-hidden="true"></i> User Management
                </a>
                <a id="IR_ID" href="@Url.Action("NtslRawFile","Recon")" class="nav-item nav-link ">
                    <i class="fa fa-file-text-o" aria-hidden="true"></i> INSTL RAW File
                </a>
                <a id="Reports_ID" href="@Url.Action("ReconReport","Reports")" class="nav-item nav-link ">
                    <i class="fa fa-bar-chart" aria-hidden="true"></i> Reports
                </a>
                <a id="NBIN_ID" href="@Url.Action("Index","NBIN")" class="nav-item nav-link">
                    <i class="fa fa-inr" aria-hidden="true"></i> NBIN IFSC Management
                </a>
                <a id="PM_ID" href="@Url.Action("PartnerManagement","Partner")" class="nav-item nav-link ">
                    <i class="fa fa-handshake-o" aria-hidden="true"></i> Partner Management
                </a>
                <a id="Adjustment_ID" href="@Url.Action("Index","AdjustmentFileManagement")" class="nav-item nav-link ">
                    <i class="fa fa-file-text-o" aria-hidden="true"></i> Adjustment File
                </a>
            </div>
        </div>
    </nav>

    <section class="main-wrapper">
        @RenderBody()
        @RenderSection("scripts", false)
    </section>

    @*<footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2019 - IndusIndAdmin - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)*@
</body>
</html>