IndusIndIMPSAdminPortal/IndusIndIMPSAdminPortal/Controllers/AdjustmentFileManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CommonLayer;
using EntityLayer;
using IndusIndIMPSAdminPortal.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Nancy.Json;
//using System.Web.Script.Serialization;

namespace IndusIndIMPSAdminPortal.Controllers
{
    public class AdjustmentFileManagementController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        #region VIEW
        [HttpGet]
        public ActionResult UploadAdjustmentFile()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CheckAdjustmentFile()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ProcessAdjustmentFile()
        {
            return View();
        }
        #endregion

        #region SaveTccRetFile 
        [HttpPost]
        public JsonResult SaveTccRetFile()
        {
            string requestTime = DateTime.Now.ToString("dd/MM/yyyy:HH-mm-ss-fff");
            string responseTime = string.Empty;
           // SessionData sessionData = null;
            string retmsg = string.Empty;
            Response res = new Response();
            try
            { 
                
                //checking count of file injected in Request object
                if (Request.Form.Files.Count > 0)
                {
                    //Request.Form.Files.
                    //sessionData = (SessionData)Session["UserSession"];
                    AdjustmentModel adjustmentModel = new AdjustmentModel();
                    res = adjustmentModel.SaveTccRetData(Request, 1000001300);
                    responseTime = DateTime.Now.ToString("dd/MM/yyyy:HH-mm-ss-fff");
                    adjustmentModel = null;
                }
                else
                {
                    res.ResponseStatus = false;
                    res.ResponseMessage = "No file is selected";
                    res.ResponseData = "";
                }
            }

            catch (Exception ex)
            {
                #region RESPONSE
                //Log Writing 
                //string classMethod = this.GetType().Name + " - " + MethodBase.GetCurrentMethod().Name + ", UserId:" + Convert.ToString(sessionData.UserId);
                //Task.Factory.StartNew(delegate { LogHelper.Writelog(classMethod, ex, LogType.Error, LogFiles.LogsError); });
                //Response
                res.ResponseStatus = false;
                res.ResponseMessage = Messages.InternalServerError;
                responseTime = DateTime.Now.ToString("dd/MM/yyyy:HH-mm-ss-fff");
                #endregion
            }
            finally
            {
                var jss = new JavaScriptSerializer();
                string jssRespose = jss.Serialize(res);
                //string logMessage = this.GetType().Name + " - " + MethodBase.GetCurrentMethod().Name + ":- " + "RequestTime: [" + requestTime + "] - ResponseTime: [" + DateTime.Now.ToString("dd/MM/yyyy:HH-mm-ss-fff") + "] ,Response : " + jssRespose + " UserId:- " + Convert.ToString(sessionData.UserId) + ", Response:- " + retmsg;
                //Task.Factory.StartNew(delegate { LogHelper.Writelog(logMessage, LogType.Information, LogFiles.LogsTxnReqRes); });
            }
            return Json(res);
        }
        #endregion

        #region checkStatusUploadedFilesTccRet
        [HttpPost]
        public JsonResult checkStatusUploadedFilesTccRet()
        {
            DateTime start = DateTime.Now;
            string UserId = string.Empty;
            Response response = new Response();
            AdjustmentModel adjustmentModel = null;
            try
            {
                UserId = 1000001310.ToString();//Session["UserId"].ToString();
                adjustmentModel = new AdjustmentModel();
                response = adjustmentModel.checkStatusUploadedFilesTccRet(Convert.ToInt64(UserId));
            }
            catch (Exception ex)
            {
                string classMethod = "ReconController - checkStatusUploadedFilesTccRet - UserId : " + UserId;
                /*Task.Factory.StartNew(delegate {
                    LogHelper.Writelog(classMethod, ex, LogType.Error, LogFiles.LogsError);
                });*/
                //Response
                response.ResponseData = string.Empty;
                response.ResponseStatus = false;
                response.ResponseMessage = "Something went wrong,checkStatusUploadedFilesTccRet - ErrorCode - R008";
            }
            finally
            {
                DateTime end = DateTime.Now;
                /*Task.Factory.StartNew(delegate {
                    LogHelper.WriteReconLog(Convert.ToString(UserId), "Status:"
                        + Convert.ToString(response.Status) + ",Message:"
                        + Convert.ToString(response.Message), "ReconController", "checkStatusUploadedFilesTccRet", "NA", start, end);
                });*/
                adjustmentModel = null;
            }
            return Json(response);
        }
        #endregion

        /*#region getTccRetList 
        public JsonResult getTccRetList()
        {
            string requestTime = DateTime.Now.ToString("dd/MM/yyyy:HH-mm-ss-fff");
            string responseTime = string.Empty;
            //SessionData sessionData = null;
            Response response = new Response();
            try
            {
                //sessionData = (SessionData)Session["UserSession"];
                string sessionKey = Convert.ToString(Session["SessionEncKey"]);
                AdjustmentModel adjustmentModel = new AdjustmentModel();
                response = adjustmentModel.getTccRetReport(sessionData.UserId, sessionKey);
                responseTime = DateTime.Now.ToString("dd/MM/yyyy:HH-mm-ss-fff");
            }

            catch (Exception ex)
            {
                #region RESPONSE
                //Log Writing 
                string classMethod = this.GetType().Name + " - " + MethodBase.GetCurrentMethod().Name + ", UserId:" + sessionData.UserId;
                Task.Factory.StartNew(delegate { LogHelper.Writelog(classMethod, ex, LogType.Error, LogFiles.LogsError); });
                //Response  
                responseTime = DateTime.Now.ToString("dd/MM/yyyy:HH-mm-ss-fff");
                response.Status = false;
                response.Message = Messages.InternalServerError;
                #endregion
            }
            finally
            {
                string logMessage = this.GetType().Name + " - " + MethodBase.GetCurrentMethod().Name + ", UserId:" + sessionData.UserId + ", Request Time: " + requestTime + ", Response Time:" + responseTime;
                Task.Factory.StartNew(delegate { LogHelper.Writelog(logMessage, LogType.Information, LogFiles.LogsTxnReqRes); });
            }
            return Json(response);
        }
        #endregion*/
    }
}

IndusIndIMPSAdminPortal/IndusIndIMPSAdminPortal/Views/AdjustmentFileManagement/CheckAdjustmentFile.cshtml
@{
    ViewData["Title"] = "Check Adjustment File";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section scripts{
    <script src="~/assets/js/jquery-3.3.1.js"></script>
    <script src="~/js/jquery.blockUI.min.js"></script>
    <script src="~/js/Adjustment/CheckAdjustmentFile.js"></script>
}

<div class="container-fluid bg-white main-container">

    <div class="form-group text-right">
        @*<button class="btn btn-aqua" data-toggle="modal" data-target="#UploadFile"><i class="fa fa-plus"></i>  Upload File</button>*@
        <button class="btn btn-aqua" data-toggle="modal" data-target="#CheckFile" onclick="location.href='@Url.Action("Index","AdjustmentFileManagement")'"><i class="fa fa-backward"></i>  BACK</button>

    </div>
    <div id="menuTccRet" class="tab-pane in active">
        <div class="top-section-heading" style="font-weight:500"><center>CHECK ADJUSTMENT FILE</center></div>
        <div class="col-sm-12 col-lg-12 col-md-12">

            <div class="col-md-1 col-sm-1 col-sm-1 pull-right">
                <input type="button" id="btnRefresh" class="btn btn-primary" value="Refresh" />
            </div>
            <div class="col-md-1 col-sm-1 col-sm-1"></div>
        </div>
        @*Table Heading*@
        <div style="padding:3%;">
            <table id="TccRetReportTable" class="table table-bordered row-border table-hover display compact" style="padding:0; width : 100%;">
                <thead>
                    <tr>
                        <th>SR. NO.</th>
                        <th>File Name</th>
                        <th>Date</th>
                        <th>Uploaded By</th>
                        <th>Remarks</th>
                        <th>Check</th>
                        <th>Reject</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>


    <div class="modal fade" id="commentTccRetRejectModal" role="dialog" style="overflow-y: initial !important;">
        <div class="modal-dialog" style="width:40%;">
            <div class="modal-content">
                <div class="modal-header" style="color: darkblue; font-weight: bolder;">
                    <button type="button" id="dismis" class="close" data-dismiss="modal" style="font-size: xx-large;">&times;</button>
                    <h4 style="font-weight: 600; color:darkblue" class="modal-title" id="myModalLabel">REJECTION DESCRIPTION</h4>
                </div>
                <div class="modal-body" id="commentTccRetRejecBody" style="max-height: calc(100vh - 200px); overflow-y: auto;">
                    <form id="frmcommentTccRetRejec" class="form-horizontal" role="form" name="frmcommentTccRetRejec">
                        <div>
                            <section class="row">
                                <div class="row  col-sm-12 col-lg-12 col-md-12">
                                    <span id="nameRMsg" style="color: olivedrab;background-color: lightgrey;font-weight: bold;"></span><br>
                                    <textarea class="form-control my-border-style1" maxlength="100" id="nameRejectionComment" name="nameRejectionComment" required></textarea>
                                    <span class="pull-right" for="nameRejectionComment"><label id="CountChar" class="" for="CountChar"> 0</label> /100</span>
                                </div><br />
                                <div class="row col-sm-12 col-lg-12 col-md-12">
                                    <br />
                                    <input type="button" id="saveRejectCommentBtn" class="col-sm-4  btn btn-primary" value="Save" />
                                    <input type="hidden" name="tccRetIdHidden" id="tccRetIdHidden">
                                </div>
                            </section>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

IndusIndIMPSAdminPortal/IndusIndIMPSAdminPortal/Views/AdjustmentFileManagement/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts{
    <link href="~/assets/css/datepicker.css" rel="stylesheet" />
    <link href="~/assets/css/pikaday.css" rel="stylesheet" />

    <script src="~/assets/js/jquery-3.3.1.js"></script>
    <script src="~/js/jquery.blockUI.min.js"></script>
    <script src="~/assets/js/pikaday.js"></script>
    <script src="~/js/Adjustment/UploadAdjustmentFile.js"></script>
    <script src="~/js/Adjustment/CheckAdjustmentFile.js"></script>
    <script src="~/js/Adjustment/ProcessAdjustmentFile.js"></script>

}

<div class="container-fluid bg-white main-container">

    <div class="form-group text-right">
        @*<button class="btn btn-aqua" data-toggle="modal" data-target="#UploadFile"><i class="fa fa-plus"></i>  Upload File</button>*@
        <button class="btn btn-aqua" data-toggle="modal" data-target="#CheckFile" onclick="location.href='@Url.Action("CheckAdjustmentFile","AdjustmentFileManagement")'"><i class="fa fa-check"></i>  Check File</button>
        <button class="btn btn-aqua" data-toggle="modal" data-target="#ProcessFile" onclick="location.href='@Url.Action("ProcessAdjustmentFile","AdjustmentFileManagement")'"><i class="fa fa-file"></i>  Process File</button>
    </div>

    <div id="menu12" class="tab-pane in active">

        <div id="divFileUploadTccRet">
            <div class="top-section-heading" style="font-weight:500"><center>UPLOAD ADJUSTMENT FILE</center></div>
            <div>
                <form id="frmTccRet" style="margin:4px;">
                    <div>
                        <section>
                            <div class="row col-lg-12 col-md-12 col-sm-12">
                                <a class="col-sm-offset-9" id="showFileUploadStatusDivTccRet" href="#"><b>GO TO FILE UPLOAD STATUS</b></a>
                            </div>
                            <div class="col-lg-12 col-md-12 col-sm-12"> </div><div class="col-lg-12 col-md-12 col-sm-12"> </div>
                            <div class="col-lg-12 col-md-12 col-sm-12"> </div><div class="col-lg-12 col-md-12 col-sm-12"> </div>
                            <div class="col-lg-12 col-md-12 col-sm-12"> </div><div class="col-lg-12 col-md-12 col-sm-12"> </div>
                            <div class="col-lg-12 col-md-12 col-sm-12"> </div><div class="col-lg-12 col-md-12 col-sm-12"> </div>
                            <div class="col-lg-12 col-md-12 col-sm-12"> </div><div class="col-lg-12 col-md-12 col-sm-12"> </div>
                            <div class="row col-lg-12 col-md-12 col-sm-12">
                                <div class="row col-lg-2 col-md-2 col-sm-2">

                                </div>
                                <div class="row col-lg-4 col-md-4 col-sm-4">
                                    <span id="MsgtxtDate" class="badge text-danger"></span>
                                </div>
                                <div class="row col-lg-2 col-md-2 col-sm-2">

                                </div>
                                <div class="row col-lg-4 col-md-4 col-sm-4">
                                    <span id="MsgTccRetFile" class="badge text-danger"></span>
                                </div>
                            </div>
                            <div class="col-lg-12 col-md-12 col-sm-12"></div>
                            <div class="col-lg-12 col-md-12 col-sm-12"></div>
                            <div class="col-lg-12 col-md-12 col-sm-12"></div>
                            <div class="col-lg-12 col-md-12 col-sm-12"></div>
                            <div class="col-lg-12 col-md-12 col-sm-12"></div>
                            <div class="col-lg-12 col-md-12 col-sm-12"></div>
                            <div class="col-lg-12 col-md-12 col-sm-12"></div>
                            <div class="col-lg-12 col-md-12 col-sm-12"></div>
                            <div class="row col-lg-12 col-md-12 col-sm-12">
                                <div class="row col-lg-2 col-md-2 col-sm-2">
                                    <label class="custom-label-cls">Date</label><span class="fail-custom-text text-bold">*</span>
                                </div>
                                <div class="row col-lg-4 col-md-4 col-sm-4">
                                    <input class="form-control my-border-style1" type="text" name="txtDate" id="txtDate" placeholder="DD/MM/YYYY" readonly="readonly" required />
                                </div>
                                <div class="row col-lg-2 col-md-2 col-sm-2">
                                    <label class="custom-label-cls">Upload Adjustment File</label><span class="fail-custom-text text-bold">*</span>
                                </div>
                                <div class="row col-lg-4 col-md-4 col-sm-4">
                                    <input class="form-control my-border-style1" style="width:85%;" type="file" id="TccRetFile" name="TccRetFile" required />
                                </div>
                            </div>

                            <div class="col-sm-12 col-lg-12 col-md-12" id="submitDiv" style="top:10px">
                                <br />
                                @*<div class="col-sm-2 col-lg-2 col-md-2"></div>*@
                                @*<div class="col-sm-4 col-lg-4 col-md-4">
                                    <input type="button" id="btnReset" class="form-control btn btn-primary custom-btn-style1" value="RESET" />
                                    </div>*@
                                <div class="row col-sm-2 col-lg-2 col-md-2 pull-right">
                                    <button id="btnUploadFile" class="btn btn-aqua" data-toggle="modal"><i class="fa fa-upload"></i>UPLOAD</button>
                                </div>
                                @*<div class="col-sm-2 col-lg-2 col-md-2"></div>*@
                            </div>
                        </section>
                    </div>
                </form>
            </div>
        </div>

        <div id="divFileUploadStatusTccRet">
            <div class="top-section-heading">FILE'S UPLOAD STATUS</div>
            <div style="padding:1%;">
                <input type="button" id="btnRefreshTccRet" class="btn btn-primary btn-xs pull-left" value="REFRESH" /> <br />
                <a id="showFileUploadDivTccRet" href="#" class="pull-right">GO BACK</a>
                <table id="recoTable" class="table table-bordered row-border table-hover display compact" style="padding:0; width : 100%;">
                    <thead>
                        <tr>
                            <th>SR. NO.</th>
                            <th>STATUS</th>
                            <th>DATE</th>
                            <th>FILE NAME</th>
                            <th>REMARK</th>
                            <th>MAKER ID</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>

    </div>
</div>

IndusIndIMPSAdminPortal/IndusIndIMPSAdminPortal/Views/AdjustmentFileManagement/ProcessAdjustmentFile.cshtml
@{
    ViewData["Title"] = "Process Adjustment File";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section scripts{
    <script src="~/assets/js/jquery-3.3.1.js"></script>
    <script src="~/js/jquery.blockUI.min.js"></script>
    <script src="~/js/Adjustment/ProcessAdjustmentFile.js"></script>
}
<div class="container-fluid bg-white main-container">

    <div class="form-group text-right">
        @*<button class="btn btn-aqua" data-toggle="modal" data-target="#UploadFile"><i class="fa fa-plus"></i>  Upload File</button>*@
        <button class="btn btn-aqua" data-toggle="modal" data-target="#CheckFile" onclick="location.href='@Url.Action("Index","AdjustmentFileManagement")'"><i class="fa fa-backward"></i>  BACK</button>

    </div>
    <div id="menuTccRet" class="tab-pane in active">
        <div class="top-section-heading" style="font-weight:500"><center>PROCESS ADJUSTMENT FILE</center></div>

        @*Table Heading*@
        <div style="padding:1%;">
            <table id="TccRetReportTable" class="table table-bordered row-border table-hover display compact" style="padding:0; width : 100%;">
                <thead>
                    <tr>
                        <th>SR. NO.</th>
                        <th>File Name</th>
                        <th>Date</th>
                        <th>Uploaded By</th>
                        <th>Remarks</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>